### PR TITLE
add a cooldown for spinning waterslice

### PR DESCRIPTION
**Pull request by CycloKid**

### CODE REVIEW

**Comment by CycloKid** [comment]
swapped png to avif
because its probably better for webpages (i think)

**Comment by CycloKid** [comment]
pixel waterslice now is MUCH smaller, like over 80 percent smaller. should make it load a whole lot faster.

**Comment by CycloKid** [comment]
check out pagespeed insights because it gives you good info on how to optimize the webpages. https://pagespeed.web.dev/analysis/https-cyclokid-github-io-pomelo-emu-github-io/y9s096a2oc?form_factor=mobile

**Comment by CycloKid** [comment]
i almost forgot to update the minified files. let me do that rq

**Comment by TechGuy541** [comment]
should i merge or not?

**Comment by CycloKid** [comment]
its good you can merge it now

**Pull request merged**
