### PR TITLE
Minor Adjustments

### PR DESCRIPTION
**Pull request by CycloKid**
See the [changes.txt](https://github.com/CycloKid/pomelo-emu.github.io/blob/new/changes.txt) file:
```
CycloKid, 2023-10-25 11AM EST
- Allowed buttons to wrap to the next line
  - This also fixes a problem with mobile browsers not being centered
- Moved title to be below Pomelo icon
- Removed arrow icons (I mean its kind of common sense to scroll down)
- Adjusted spacing to make the hero section take up the entire page when entering (needs testing)
  - Right now, theres a -probably- hacky solution for mobile browsers. Might need to be addressed in the future.
- Adjusted about section text
- Update minified files
```

### CODE REVIEW

**Comment by CycloKid** [comment]
i highly recommend setting gh pages to use the /public/ directory to make load times much faster

**Comment by CycloKid** [comment]
if you need to update the site, all you need to do is edit the unminified files at the root of the repo and then replace the minified files in ./public/
personally i use the "Minify" VSCode extension because all you need to do is highlight your files and then select Minify in the command palette.

**Comment by TechGuy541** [comment]
thanks for update

**Comment by CycloKid** [comment]
no problem :) thx for merging

**Pull request merged**
